from pathlib import Path
from datetime import datetime
import pandas as pd

data = Path("data/records.csv")
reports = Path("reports"); reports.mkdir(parents=True, exist_ok=True)
out = reports / "ultimo_report.md"

if not data.exists():
    with out.open("a", encoding="utf-8") as f:
        f.write("\n_(records.csv mancante: nessun dato da analizzare)_\n")
    raise SystemExit(0)

df = pd.read_csv(data)

if "anno" in df.columns:
    df["anno"] = pd.to_numeric(df["anno"], errors="coerce")

now = datetime.now().strftime("%Y-%m-%d %H:%M")

# ultimi ~12 mesi se c'è la colonna anno (grezzo)
recent = df
if df["anno"].notna().any():
    recent = df[df["anno"] >= df["anno"].max() - 1]

by_fest = recent.groupby("festival")["opera"].count().sort_values(ascending=False)

keys = ["linguaggio","drammaturgia","innovazione","politico","sociale","corpo","regia","ibridazione","struttura","emotivo"]
motifs = {k:0 for k in keys}
for s in df.get("motivazione", pd.Series(dtype=str)).dropna().astype(str).str.lower():
    for k in keys:
        if k in s:
            motifs[k] += 1
motifs_series = pd.Series(motifs).sort_values(ascending=False)

parts = []
parts.append("## Trend ultimi 12 mesi (conteggio opere segnalate)")
parts.append(by_fest.to_markdown() if len(by_fest) else "_Nessun dato_")
parts.append("\n## Pattern ricorrenti nelle motivazioni")
parts.append(motifs_series.to_frame("occorrenze").to_markdown() if motifs_series.sum() else "_Nessun pattern rilevato_")

with out.open("a", encoding="utf-8") as f:
    f.write("\n".join(parts) + "\n")
