name: Monitor festival (pulito)

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install pandas

      - name: Archivia pagine
        run: bash scripts/archive_pages.sh

      - name: Genera report
        run: python scripts/generate_report.py

      - name: Commit automatico
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "crawl+report: aggiornamento settimanale"
          file_pattern: |
            data/raw/**
            reports/ultimo_report.md
            config/sources.txt
            scripts/**
