name: Monitor festival (pulito)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout completo del repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Allinea con main prima di lavorare
      - name: Allinea con origin/main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main || true

      # 3. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 4. Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      # 5. Esegui lo script principale
      - name: Genera report
        run: |
          chmod +x scripts/archive_pages.sh
          ./scripts/archive_pages.sh
          python scripts/generate_report.py

      # 6. Commit e push dell'aggiornamento
      - name: Commit e push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: aggiornamento report"
          file_pattern: reports/ultimo_report.md
          push_options: --force-with-lease
