name: Monitor festival (definitivo, niente conflitti)

on:
  workflow_dispatch: {}     # lo avvii solo tu, a mano

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configura git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # AZZERAMENTO CONFLITTI: allinea sempre al remoto, buttando via lo stato locale del runner
      - name: Hard reset su origin/main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install pandas || true

      - name: Esegui script
        run: |
          chmod +x scripts/archive_pages.sh || true
          ./scripts/archive_pages.sh || true
          python scripts/generate_report.py

      # COMMIT MANUALE, SENZA ACTION ESTERNE
      - name: Commit e push forzato del report
        run: |
          git add -A
          git commit -m "report: aggiornamento" || echo "Niente da committare"
          git push origin HEAD:main --force
