name: ZZZ WORKFLOW TEST

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "WORKFLOW ATTIVO OK"
          echo "FILE CORRENTE: $GITHUB_WORKFLOW_REF"
