name: Monitor festival (pulito)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout completo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configura Git
      - name: Configura Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. Sincronizza con main per evitare conflitti
      - name: Allinea con main
        run: |
          git pull --rebase origin main || true

      # 4. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 5. Installa dipendenze
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      # 6. Esegui gli script
      - name: Esegui script
        run: |
          chmod +x scripts/archive_pages.sh
          ./scripts/archive_pages.sh
          python scripts/generate_report.py

      # 7. Commit e push forzato
      - name: Commit e push
        run: |
          git add reports/ultimo_report.md
          git commit -m "chore: aggiornamento report" || echo "Nessuna modifica da commitare"
          git push origin main --force
